### ISSUE TITLE
QStorageInfo isn't available on QT 5.3

### ISSUE THREAD

**Issue by alexarnaud** [port-42/server#4]
Dear team,

At you can see on the Debian repo here : https://packages.debian.org/jessie/qt5-default
The documentation of the function : http://doc.qt.io/qt-5/qstorageinfo.html

So only one solution : finding another way to store our data.

I'll look more deeply on the source code and the C++/QT documentation. 

Best regards.

**Comment by alexarnaud** [comment]
It seems there are the class named "QSystemStorageInfo" from QT Mobility that can help you on our work.
Cf. on stackoverflow : http://stackoverflow.com/a/13252661
cf. the QT Documentation : https://doc-snapshots.qt.io/qt-mobility/qsystemstorageinfo.html

If I found the time this week-end I'll take a look on that.

**Comment by FloGro** [comment]
QSystemInfo wasn't used in debian, only on windows (wich is using qt > 5.4).
So I added a macro Q_VERSION defining if we are using QSystemInfo or not.
Correction is in the last pull request.(https://github.com/port-42/server/pull/5).

:)
